### ISSUE TITLE
VoyantServer - SSL settings available ?

### ISSUE THREAD

**Issue by pguerr061703** [sgsinclair/VoyantServer#15]

**Comment by sgsinclair** [comment]
As I mentioned in my email, you don't seem to be listening to the secure port in your proxy server (Apache). If you do, you should be able to proxy requests to an instance of Voyant running under Jetty (on whatever local port).

**Comment by pguerr061703** [comment]
n/a

**Comment by sgsinclair** [comment]
Oh, I thought I'd seen in your email a < VirtualHost > section. Anyway, I honestly don't know if the embedded Jetty server even supports SSL, so the assumption is that you'd be using nginx or apache as a front end.

The main (secure) server https://voyant-tools.org/ uses Apache to proxy an instance of Voyant running under Tomcat. I suspect I tried some simpler solutions and this is the one that I ended up getting to work. I'm happy to share any config files that could be of use.

**Comment by pguerr061703** [comment]
n/a

**Comment by pguerr061703** [comment]
n/a

**Comment by sgsinclair** [comment]
Again, I'm not entirely sure about your setup, but somewhere along the way the server thinks it's running on port 80 instead of a secure port. And like I said before, I'm not sure the embedded version of Jetty will work, you might need to try running Voyant inside of Tomcat. But I wouldn't recommend fiddling with SSL certificates within Tomcat, which is why I've set things up so that Apache received SSL requests and proxies them to Tomcat (and Tomcat has been specially configured to know that it's running SSL).

We could maybe make some progress if we were sitting together working on it, but I'm not sure I'll be of any further use, except to suggest again that you try to create a setup that has been proved to work.

**Comment by pguerr061703** [comment]
n/a

**Comment by sgsinclair** [comment]
You have new mail.
