### ISSUE TITLE
stopword list is no longer global

### ISSUE THREAD

**Issue by melvinwevers** [sgsinclair/VoyantServer#2]
In this previous version (V1?), you could define a global stopword list which would work within all tools. Now stopwords only work within the word cloud, which makes most of the other tools unusable. Is there a fix for this problem?

**Comment by sgsinclair** [comment]
Thanks! The UI should be fixed in the next release (within a couple of weeks), but for now here's an awkward workaround:

1) set the stopword list in Cirrus
2) export the URL from Cirrus (export icon, click first link)
3) remove &view=Cirrus from the resulting URL

BTW, stopword lists can now be reused between corpora (unlike in V1).

**Comment by sgsinclair** [comment]
fixed in 2.0 M4
